name: Test Both Repos

on:
  push:
    branches:
      - main

jobs:
  HIDDEN:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo (for shared code)
      uses: actions/checkout@v2

    - name: Write secret key to config
      run: echo "ANSWER=${{ secrets.ANSWER }}" > env.txt

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3