name: Test Both Repos

on:
  push:
    branches:
      - main

jobs:
  VISIBLE:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run pytest from public repo
      run: pytest visible.py

  HIDDEN:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow in hidden_test
      run: |
        gh api repos/insper-education/hidden_test/dispatches \
          --header "Accept: application/vnd.github.v3+json" \
          --raw-field event_type=run-pytest
      env:
        GH_TOKEN: ${{ secrets.INSPER_BOT }}